### ISSUE TITLE
Tracking: StarCoder for Enterprise

### ISSUE THREAD

**Issue by kalanchan** [kalanchan/pfp-test#1]
> [!note]
>This is an epic-style issue for tracking/grouping issues only, used to track our progress towards the Feb launch event.

[RFC 849](https://docs.google.com/document/d/1LgBhvRI0S7CdHPlsgq6icwLMoJlu7ffZA2t-2rYPyB8/edit)
[PRD: StarCoder For Enterprise](https://docs.google.com/document/d/1MKP2VUwFCOfHt8nllN8hRC_o84LFSVUg4Lh2mYleZ90/edit#heading=h.kh25fry1pv3d)
[Working Doc](https://docs.google.com/document/d/1P-Hb8BTbz-vMNFXw3gbAvphArsNvS1_8u4ID-phn8gI/edit#heading=h.kgzzoc2kqxri)

```[tasklist]
### Starcoder for Enterprise:
- [ ] #2 
- [ ] hello
- [ ] hello
- [ ] lol
- [ ] random
- [ ] test
- [ ] whatsup
- [X] ahhhh
- [ ] https://github.com/kalanchan/kalan-test/issues/14
- [ ] https://github.com/kalanchan/kalan-test/issues/13
- [ ] https://github.com/kalanchan/kalan-test/issues/11
- [ ] https://github.com/kalanchan/kalan-test/issues/10
```
